# Generated by Django 5.1.2 on 2024-10-19 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_system', '0007_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='last_login',
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='user_agent',
            field=models.CharField(max_length=256),
        ),
    ]
