# Generated by Django 5.1.2 on 2024-10-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_system', '0008_remove_device_last_login_device_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='created_at',
        ),
        migrations.AddField(
            model_name='device',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
